###
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "name":"Nguyen Nhat Hao",
  "email":"haonhat2729@gmail.com",
  "password":"123456",
  "phoneNumber":"0123456789",
  "public_id":null,
  "gender":true
}

###
POST http://localhost:3001/auth/signout

###
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "email":"haonhat2729@gmail.com",
  "password":"123456"
}